"""initial schema

Revision ID: 31ade931cfe1
Revises: 
Create Date: 2026-06-12 21:40:54.010025

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '31ade931cfe1'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('hashed_password', sa.String(length=255), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_users_email'), ['email'], unique=True)

    op.create_table('sessions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('label', sa.String(length=255), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('sessions', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_sessions_user_id'), ['user_id'], unique=False)

    op.create_table('records',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('session_id', sa.Integer(), nullable=True),
    sa.Column('item_name', sa.String(length=512), nullable=True),
    sa.Column('barcode', sa.String(length=64), nullable=True),
    sa.Column('manufacturer', sa.String(length=255), nullable=True),
    sa.Column('brand', sa.String(length=255), nullable=True),
    sa.Column('weight_value', sa.Float(), nullable=True),
    sa.Column('weight_unit', sa.String(length=16), nullable=True),
    sa.Column('packaging_type', sa.String(length=128), nullable=True),
    sa.Column('country_of_origin', sa.String(length=128), nullable=True),
    sa.Column('variant_type', sa.String(length=128), nullable=True),
    sa.Column('fragrance_flavor', sa.String(length=255), nullable=True),
    sa.Column('promotion', sa.String(length=512), nullable=True),
    sa.Column('addons', sa.String(length=512), nullable=True),
    sa.Column('tagline', sa.String(length=512), nullable=True),
    sa.Column('category_type', sa.String(length=128), nullable=True),
    sa.Column('confidence', sa.JSON(), nullable=False),
    sa.Column('source', sa.JSON(), nullable=False),
    sa.Column('needs_review', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['session_id'], ['sessions.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('records', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_records_barcode'), ['barcode'], unique=False)
        batch_op.create_index(batch_op.f('ix_records_brand'), ['brand'], unique=False)
        batch_op.create_index(batch_op.f('ix_records_session_id'), ['session_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_records_user_id'), ['user_id'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('records', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_records_user_id'))
        batch_op.drop_index(batch_op.f('ix_records_session_id'))
        batch_op.drop_index(batch_op.f('ix_records_brand'))
        batch_op.drop_index(batch_op.f('ix_records_barcode'))

    op.drop_table('records')
    with op.batch_alter_table('sessions', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_sessions_user_id'))

    op.drop_table('sessions')
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_users_email'))

    op.drop_table('users')
    # ### end Alembic commands ###
